CREATE DATABASE MYFLASKAPP;

USE MYFLASKAPP;

CREATE TABLE USERS(
	id int(11) AUTO_INCREMENT PRIMARY KEY,
	name varchar(255),
	username varchar(30),
	email varchar(30),
	password varchar(100),
	register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE ARTICLES(
	id int(11) AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255),
	author VARCHAR(20),
	body text,
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

SHOW TABLES

SELECT * FROM USERS

SELECT * FROM ARTICLES

DELETE FROM USERS